AWSTemplateFormatVersion: '2010-09-09'
Description: "Ec2 instances template"

Parameters:
  AMIID: 
    Description: "EC2 Image ID"
    Type: String
    Default: "ami-00c39f71452c08778"
  InstanceType:
    Description: "Type of EC2 instance"
    Type: String
    Default: "t2.micro"

Resources:
  webserver:
    Type: AWS::EC2::Instance
    Properties:
       ImageId: !Ref AMIID
       InstanceType: !Ref InstanceType
       BlockDeviceMappings: 
       -  DeviceName: "/dev/xvda"
          Ebs: 
            VolumeType: "io1"
            Iops: "200"
            DeleteOnTermination: "true"
            VolumeSize: "8"
 
     