AWSTemplateFormatVersion: '2010-09-09'
Description: "Ec2 instances template"

Parameters:
  InstanceType:
    Description: "Type of EC2 instance"
    Type: String
    Default: "t2.micro"

Mappings:
  RegionMap:
    us-east-1:
      "linux": "ami-00c39f71452c08778"
    us-west-1:
      "linux": "ami-0bdb828fd58c52235"
    eu-west-1:
      "linux": "ami-047bb4163c506cd98"
    ap-southeast-1:
      "linux": "ami-08569b978cc4dfa10"
    ap-northeast-1:
      "linux": "ami-06cd52961ce9f0d85"
    us-west-2:
      "linux": "ami-0efa651876de2a5ce"
Resources:
  webserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", linux]
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: true
          VolumeSize: "8"